export const SET_WEB3 = "SET INITIALED WEB3";
export const SET_REFRESH_ID = "SET REFRESH ACCOUNT ID";
export const SET_CONTRACT = "SET CONTRACT";
export const SET_UNSUBSCRIBE = "SET UNSUBSCRIBE";
export const ADD_UNSUBSCRIBE = "ADD UNSUBSCRIBE OBJECT";
export const SET_UNSUBSCRIBE_NAMES = "SET UNSUBSCRIBE NAMES";
export const ADD_UNSUBSCRIBE_NAMES = "ADD UNSUBSCRIBE NAMES";

export const SET_ACCOUNT = "SET ACCOUNT ADDRESS";
export const SET_BALANCE = "SET BALANCE";
export const SET_ACCOUNT_INFO = "SET_ACCOUNT_INFO";

export const INPUT_FIO_REG = "INPUT FIO REG";
export const INPUT_LOGIN_REG = "INPUT LOGIN REG";
export const INPUT_PASSWORD_REG = "INPUT PASSWORD REG";
export const START_REG = "START GER";
export const ABORT_REG = "ABORT REG";
export const END_REG = "END REG";

export const INPUT_LOGIN_LOG = "INPUT LOGIN ON LOGIN PAGE";
export const INPUT_PASSWORD_LOG = "INPUT PASSWORD ON LOGIN PAGE";
export const START_LOGIN = "START LOGIN IN ACCOUNT";
export const ABORT_LOGIN = "ABORT LOGIN IN ACCOUNT";
export const LOGGED = "LOGGED IN ACCOUNT";

export const CHANGE_ROLE = "CHANGE YOUR ROLE";
export const NEW_ROLE = "SET NEW CONSTANTS ROLE";

export const SET_SHOPS = "SET SHOPS";
export const SET_SALESMEN = "SET SALESMEN FOR SHOP";
export const ADD_SHOP = "ADD NEW SHOP";
export const REMOVE_SHOP = "REMOVE SHOP";
export const ADD_SALESMAN = "ADD SALESMAN TO THE SHOP";
export const REMOVE_SALESMAN = "REMOVE SALESMAN FROM THE SHOP";
export const TOGGLE_SHOW_SALESMEN = "SHOW OR HIDDEN SALESMEN";
export const SET_COMPLAINS_AND_SUGGESTIONS =
  "SET COMPLAINS AND SUGGESTIONS BOOK";
export const CHANGE_MARK = "CHANGE MARK";

export const INPUT_NEW_COMMENT = "INPUT NEW COMMENT";
export const INPUT_NEW_MARK = "INPUT_NEW_MARK"; //I don'n know how it's supposed to work
export const ADD_CAS = "ADD NEW CAS";
export const TOGGLE_SHOW_WINDOW = "TOGGLE SHOW WINDOW FOR NEW MESSAGE";
export const START_SEND_COMMENT = "START SEND COMMENT";
export const ABORT_SEND_COMMENT = "ABORT SEND COMMENT";
export const END_SEND_COMMENT = "COMMENT WAS SENDED SUCCESFUL";

export const BE_SET_ADMIN_REQUESTS = "SET REQUEST FOR BE ADMIN"; //??
export const BE_SET_SALESMAN_REQUESTS = "SET REQUESTS FOR BE SALESMAN";
export const BE_SET_BUYER_REQUESTS = "SET REQUESTS FRO BE BUYER";
export const ADD_REQUEST = "ADD REQUEST BY ACTION FILTER";
export const FINISH_REQUEST = "REQUEST WAS FINISHED";

export const SET_USERS = "SET ALL USERS OF CONTRACT";
export const REMOVE_USER = "REMOVE USER WHEN HIS ACCOUNT BECOMES A STORE";
export const CHANGE_ROLE_USERS = "CHANGE ROLE USER";
export const NEW_ROLE_USERS = "NEW ROLE FOR USER";
export const ADD_USER = "ADD NEW USER";
