export const START_LOADING = "START LOADING";
export const SET_WEB3 = "SET INITIALED WEB3";
export const SET_REFRESH_ID = "SET REFRESH ACCOUNT ID";
export const SET_CONTRACT = "SET CONTRACT";
export const SET_UNSUBSCRIBE = "SET UNSUBSCRIBE";
export const ADD_UNSUBSCRIBE = "ADD UNSUBSCRIBE OBJECT";
export const SET_UNSUBSCRIBE_NAMES = "SET UNSUBSCRIBE NAMES";
export const ADD_UNSUBSCRIBE_NAMES = "ADD UNSUBSCRIBE NAMES";

export const SET_ACCOUNT = "SET ACCOUNT ADDRESS";
export const SET_BALANCE = "SET BALANCE";
export const SET_ACCOUNT_INFO = "SET_ACCOUNT_INFO";
export const SET_ACCOUNT_SHOP = "SET SPECIAL ACCOUNT INFO WHEN USER IS SHOP";
export const SET_ACCOUNT_SALESMEN = "SET ACCOUNT SALESMEN WHEN USER IS SHOP";

export const END_REG = "END REG";

export const LOGGED = "LOGGED IN ACCOUNT";
export const GUEST_ENTER = "ENTER AS A GUEST";

export const CHANGE_ROLE = "CHANGE YOUR ROLE";
export const NEW_ROLE = "SET NEW CONSTANTS ROLE";

export const SET_SHOPS = "SET SHOPS";
export const SET_SALESMEN = "SET SALESMEN FOR SHOP";
export const ADD_SHOP = "ADD NEW SHOP";
export const REMOVE_SHOP = "REMOVE SHOP";
export const ADD_SALESMAN = "ADD SALESMAN TO THE SHOP";
export const REMOVE_SALESMAN = "REMOVE SALESMAN FROM THE SHOP";
export const SET_COMPLAINS_AND_SUGGESTIONS =
  "SET COMPLAINS AND SUGGESTIONS BOOK";
export const CHANGE_CAS_MARK = "CHANGE CAS MARK";
export const SET_COMMENTS = "SET CAS'S COMMENTS";
export const ADD_COMMENT = "ADD CAS'S COMMENT";
export const CHANGE_COMMENT_MARK = "CHANGE COMMENT MARK";

export const ADD_CAS = "ADD NEW CAS";

export const BE_SET_ADMIN_REQUESTS = "SET REQUEST FOR BE ADMIN";
export const BE_SET_SALESMAN_REQUESTS = "SET REQUESTS FOR BE SALESMAN";
export const BE_SET_BUYER_REQUESTS = "SET REQUESTS FRO BE BUYER";
export const ADD_REQUEST = "ADD REQUEST BY ACTION FILTER";
export const FINISH_REQUEST = "REQUEST WAS FINISHED";
export const FINISH_BANK_REQUEST = "BANK REQUEST WAS FINISHED";
export const SET_BANK_REQUESTS = "SET REQUEST TO BANK";

export const SET_USERS = "SET ALL USERS OF CONTRACT";
export const REMOVE_USER = "REMOVE USER WHEN HIS ACCOUNT BECOMES A STORE";
export const CHANGE_ROLE_USERS = "CHANGE ROLE USER";
export const NEW_ROLE_USERS = "NEW ROLE FOR USER";
export const ADD_USER = "ADD NEW USER";
export const SET_FREE_ADDRESSES = "SET FREE ADDRESSES";
export const ADD_FREE_ADDRESS = "ADD FREE ADDRESS";
export const REMOVE_FREE_ADDRESS = "REMOVE FREE ADDRESS";
