export const SET_WEB3 = "SET INITIALED WEB3";
export const SET_REFRESH_ID = "SET REFRESH ACCOUNT ID";
export const SET_CONTRACT = "SET CONTRACT";
export const SET_UNSUBSCRIBE = "SET UNSUBSCRIBE";

export const SET_ACCOUNT = "SET ACCOUNT ADDRESS";
export const SET_BALANCE = "SET BALANCE";
export const SET_ACCOUNT_INFO = "SET_ACCOUNT_INFO";

export const INPUT_FIO_REG = "INPUT FIO REG";
export const INPUT_LOGIN_REG = "INPUT LOGIN REG";
export const INPUT_PASSWORD_REG = "INPUT PASSWORD REG";
export const START_REG = "START GER";
export const ABORT_REG = "ABORT REG";
export const END_REG = "END REG";

export const INPUT_LOGIN_LOG = "INPUT LOGIN ON LOGIN PAGE";
export const INPUT_PASSWORD_LOG = "INPUT PASSWORD ON LOGIN PAGE";
export const START_LOGIN = "START LOGIN IN ACCOUNT";
export const ABORT_LOGIN = "ABORT LOGIN IN ACCOUNT";
export const LOGGED = "LOGGED IN ACCOUNT";

export const CHANGE_ROLE = "CHANGE YOUR ROLE";
export const NEW_ROLE = "SET NEW CONSTANTS ROLE";

export const SET_SHOPS = "SET SHOPS";
export const SET_SALESMEN = "SET SALESMEN FOR SHOP";
export const ADD_SHOP = "ADD NEW SHOP";
export const TOGGLE_SHOW_SALESMEN = "SHOW OR HIDDEN SALESMEN";
export const SHOP_CARD = "SHOP CARD CONNECT";
export const SET_COMPLAINS_AND_SUGGESTIONS =
  "SET COMPLAINS AND SUGGESTIONS BOOK";
export const SHOW_COMPLAINS_AND_SUGGESTIONS = "SHOW COMPLAINS AND SUGGESTIONS";
export const CHANGE_MARK = "CHANGE MARK";

export const INPUT_NEW_COMMENT = "INPUT NEW COMMENT";
export const INPUT_NEW_MARK = "INPUT_NEW_MARK"; //I don'n know how it's supposed to work
export const ADD_CAS = "ADD NEW CAS";
export const TOGGLE_SHOW_WINDOW = "TOGGLE SHOW WINDOW FOR NEW MESSAGE";
export const START_SEND_COMMENT = "START SEND COMMENT";
export const ABORT_SEND_COMMENT = "ABORT SEND COMMENT";
export const END_SEND_COMMENT = "COMMENT WAS SENDED SUCCESFUL";
