export const MAIN = "MAIN CONNECT";

export const LOGIN = "LOGIN CONTAINER";
export const LOGIN_LOGIN = "LOGIN FIELD OF LOGIN PAGE";
export const LOGIN_PASSWORD = "PASSWORD FIELD OF LOGIN PAGE";
export const LOGIN_BUTTON = "BUTTON OF LOGIN PAGE";

export const REGISTRATION = "REG CONNECT";
export const REG_FIO = "REG FIO";
export const REG_PASSWORD = "REG PASSWORD";
export const REG_LOGIN = "REG LOGin";
export const REG_BUTTON = "REG BUTTON";

export const ACCOUNT = "ACCOUNT PAGE CONNECT";
export const BE_BUYER = "BUTTON FOR BE BUYER";
export const BE_SALESMAN = "BUTTON FOR BE SALESMAN";
export const BE_ADMIN = "BUTTON FOR BE ADMIN";
export const BE_BUYER_FOREVER = "BUTTON FOR BE BUYER FOREVER";
export const BE_SALESMAN_OF_SHOP = "BE SALESMAN OF THE SHOP";

export const SHOPS_LIST = "SHOPS LIST CONNECT";
export const SHOW_SALESMEN_BUTTON = "SHOW SALESMEN OF SHOP";
export const SALESMEN_LIST = "SALESMEN LIST";
export const CAS_LIST = "COMPLAIN AND SUGGESTION LIST CONNECT";
export const CAS_ITEM = "COMPLAIN AND SUGGESTION ITEM CONNECT";
export const LIKE_BUTTON = "LIKE BUTTON";
export const DISLIKE_BUTTON = "DISLIKE BUTTON";
export const SHOP_CARD = "SHOP CARD CONNECT";

export const COMMENT_FIELD = "COMMENT FIELD";
export const MARK_FIELD = "MARK FIELD";
export const SEND_COMMENT_BUTTON = "SEND BUTTON CONNECT";
export const NEW_COMMENT = "NEW COMMENT CONNECT";

export const SALESMAN_CONTENT = "SALESMAN CONNECT";

export const ADMIN_REQUESTS = "REQUESTS LIST FOR BE ADMIN";
export const SALESMAN_REQUESTS = "REQUESTS LIST FOR BE SALESMAN";
export const BUYER_REQUESTS = "REQUESTS LIST FRO BE BUYER";
export const CANCEL_BUYER_REQUEST = "CANCEL BUYER REQUEST BUTTON";
export const ACCEPT_BUYER_REQUEST = "ACCEPT BUYER REQUEST BUTTOn";
