export const MAIN = "MAIN CONNECT";

export const LOGIN = "LOGIN CONTAINER";
export const LOGIN_LOGIN = "LOGIN FIELD OF LOGIN PAGE";
export const LOGIN_PASSWORD = "PASSWORD FIELD OF LOGIN PAGE";
export const LOGIN_BUTTON = "BUTTON OF LOGIN PAGE";

export const REGISTRATION = "REG CONNECT";
export const REG_FIO = "REG FIO";
export const REG_PASSWORD = "REG PASSWORD";
export const REG_LOGIN = "REG LOGin";
export const REG_BUTTON = "REG BUTTON";

export const ACCOUNT = "ACCOUNT PAGE CONNECT";
export const BE_BUYER = "BUTTON FOR BE BUYER";
export const BE_SALESMAN = "BUTTON FOR BE SALESMAN";
export const BE_ADMIN = "BUTTON FOR BE ADMIN";

export const SHOPS_LIST = "SHOPS LIST CONNECT";
export const SHOW_SALESMEN_BUTTON = "SHOW SALESMEN OF SHOP";
export const SALESMEN_LIST = "SALESMEN LIST";
export const SHOW_COMPLAINS_AND_SUGGESTION_BUTTON = "GET CANDS BUTTON";
export const CAS_LIST = "COMPLAIN AND SUGGESTION LIST CONNECT";
export const LIKE_BUTTON = "LIKE BUTTON";
export const DISLIKE_BUTTON = "DISLIKE BUTTON";

export const COMMENT_FIELD = "COMMENT FIELD";
export const MARK_FIELD = "MARK FIELD";
export const SEND_COMMENT_BUTTON = "SEND BUTTON CONNECT";
export const NEW_COMMENT = "NEW COMMENT CONNECT";
export const SHOW_NEW_COMMENT = "SHOW NEW COMMENT";
