export const MAIN = "MAIN CONNECT";

export const LOGIN = "LOGIN CONTAINER";
export const GUEST_BUTTON = "ENTER AS GUEST BUTTON";

export const REGISTRATION = "REG CONNECT";

export const ACCOUNT = "ACCOUNT PAGE CONNECT";
export const BE_BUYER = "BUTTON FOR BE BUYER";
export const BE_SALESMAN = "BUTTON FOR BE SALESMAN";
export const BE_ADMIN = "BUTTON FOR BE ADMIN";
export const BE_BUYER_FOREVER = "BUTTON FOR BE BUYER FOREVER";
export const BE_SALESMAN_OF_SHOP = "BE SALESMAN OF THE SHOP";

export const SHOPS_LIST = "SHOPS LIST CONNECT";
export const SHOW_SALESMEN_BUTTON = "SHOW SALESMEN OF SHOP";
export const SALESMEN_LIST = "SALESMEN LIST";
export const CAS_LIST = "COMPLAIN AND SUGGESTION LIST CONNECT";
export const COMMENT_LIST = "COMMENT LIST CONNECT";
export const CAS_ITEM = "COMPLAIN AND SUGGESTION ITEM CONNECT";
export const LIKE_CAS_BUTTON = "LIKE CAS BUTTON";
export const DISLIKE_CAS_BUTTON = "DISLIKE CAS BUTTON";
export const SHOP_CARD_BUYER = "BUYER'S SHOP CARD CONNECT";
export const LIKE_COMMENT_BUTTON = "LIKE COMMENT BUTTON";
export const DISLIKE_COMMENT_BUTTON = "DISLIKE COMMENT BUTTON";
export const COMMENT_BUYER_CARD = "COMMENT BUYER CARD CONNECT";
export const NEW_COMMENT = "New";

export const CAS_BUTTON = "COMMENT FIELD";
export const MARK_FIELD = "MARK FIELD";
export const NEW_CAS_BUTTON = "SEND BUTTON CONNECT";
export const NEW_CAS = "NEW COMMENT CONNECT";

export const SALESMAN_CONTENT = "SALESMAN CONNECT";

export const ADMIN_REQUESTS = "REQUESTS LIST FOR BE ADMIN";
export const SALESMAN_REQUESTS = "REQUESTS LIST FOR BE SALESMAN";
export const BUYER_REQUESTS = "REQUESTS LIST FRO BE BUYER";
export const CANCEL_BUYER_REQUEST = "CANCEL BUYER REQUEST BUTTON";
export const ACCEPT_BUYER_REQUEST = "ACCEPT BUYER REQUEST BUTTON";
export const CANCEL_SALESMAN_REQUEST = "CANCEL SALESMAN REQUEST BUTTON";
export const ACCEPT_SALESMAN_REQUEST = "ACCEPT SALESMAN REQUEST BUTTON";
export const CANCEL_ADMIN_REQUEST = "CANCEL ADMIN REQUEST BUTTON";
export const ACCEPT_ADMIN_REQUEST = "ACCEPT ADMIN REQUEST BUTTON";
export const REMOVE_SHOP_BUTTON = "REMOVE SHOP BUTTON";

export const USERS = "USERS CONNECT";
export const USERS_LIST = "USERS LIST CONNECT";
export const SET_SHOP = "SET ADDRESS TO SHOP BUTTON";
export const SET_ADMIN = "SET ADDRESS TO ADMIN BUTTON";
